config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  root to: "searches#index"

  post 'flag_video', to: 'concerts#flag_video', as: 'flag_video'
  post 'unflag_video', to: 'concerts#unflag_video', as: 'unflag_video'
  get 'search', to: 'searches#search', as: 'search'
  get 'search_youtube', to: 'searches#search_youtube', as: 'search_youtube'
  get 'search_setlist', to: 'searches#search_setlist', as: 'search_setlist'
  resources :concerts, only: [:new, :create, :show]
  resources :venues, only: [:new, :create]
  resources :artists, only: [:new, :create]
  resources :songs, only: [:new, :create]
  resources :concert_songs, only: [:create]

  post 'create_concert', to: 'concerts#create', as: 'create_concert'

  resources :users, only: [:index, :show]

  resources :attended_concerts, only: [:create]

  resources :relationships, only: [:create] do
    collection do
      post '/unfollow', to: "relationships#unfollow"
    end
  end

  resources :concert_photos, only: [:create, :destroy]

  resources :pages, only: [:index]
  get 'about', to: 'pages#index', as: 'about'

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
  end

  def search
    band_query = params[:band]
    @band = Artist.find_or_initialize_by(name: band_query)
    mb_result = @band.mbid || Musicbrainz.search(@band.name)
    if mb_result
      returned_setlists = JSON.parse(Net::HTTP.get_response(
                  URI.parse("http://api.setlist.fm/rest/0.1/artist/#{mb_result}/setlists.json")
                 ).body)
      setlists_returned = returned_setlists["setlists"]["@total"]
      @max_pages = (setlists_returned.to_i / 20) + 1
      @results = Setlistfm.new(mb_result, params[:page]).search
      save_band(@band, mb_result) if @band.id.nil?
    else
      flash.now[:warning] = "Sorry - we couldn't find an artist with that name."
      redirect_to root_path
    end
  end

  def search_youtube
    @band = Artist.find_by_name(params[:band])
    search_params = params[:concert].split(', ')

    #===============================================
    #search if the concert already exists
    search_date = search_params[0]

    #If the venue doesn't exist, there has never been a show there
    #therefore go right to making the concert
    @venue = Venue.find_or_create_by(name: search_params[2])

    if @venue != nil

      #if the venue does exist, search for a concert that took place at that venue
      #on this specific date
      @concerts = Concert.where(venue_id: @venue.id, date: search_date)

      matched_concert_ids = @concerts.map { |concert| concert.id }

      #to account for festivals go through every possible artist that played
      #that venue on that specific day
      matched_concert_ids.each do |concertID|
        unless ConcertArtist.where(concert_id: concertID, artist_id: @band.id).empty?
          @concert = Concert.find(concertID)
        end
      end

      if @concert
        redirect_to @concert
      else
        save_concert(params)
        search1 = "#{@band.name}, #{@venue.name}, #{@venue.state}, #{@date}"
        search2 = "#{@band.name}, #{@venue.name}, #{@date}"
        search3 = "#{@band.name}, #{@venue.state}, #{@date}"
        # A couple more search options
        # search4 = "#{@band.name}, #{@tour}, #{@date}"
        # search5 = "#{@band.name}, #{@tour}, #{@venue.name}"

        @titles_ids = {}

        results = []

        results << Youtube.search(search1)
        results << Youtube.search(search2)
        results << Youtube.search(search3)

        results.flatten!.uniq!

        results.each do |result|
          if result =~ /\(\w*\)\z/
            title = result.gsub(/ \(\w*\)\z/, '')
            @titles_ids[title] = result[/\(\w*\)\z/].gsub(/\(*\)*/, '')
          end
        end
      end

    else

      save_concert(params)
      search1 = "#{@band.name}, #{@venue.name}, #{@venue.state}, #{@date}"
      search2 = "#{@band.name}, #{@venue.name}, #{@date}"
      search3 = "#{@band.name}, #{@venue.state}, #{@date}"
      # A couple more search options
      # search4 = "#{@band.name}, #{@tour}, #{@date}"
      # search5 = "#{@band.name}, #{@tour}, #{@venue.name}"

      @titles_ids = {}

      results = []

      results << Youtube.search(search1)
      results << Youtube.search(search2)
      results << Youtube.search(search3)

      results.flatten!.uniq!

      results.each do |result|
        if result =~ /\(\w*\)\z/
          title = result.gsub(/ \(\w*\)\z/, '')
          @titles_ids[title] = result[/\(\w*\)\z/].gsub(/\(*\)*/, '')
        end
      end
    end
  end

  private
    def save_band(band, result)
      band.mbid = result
      band.save!
    end

    def save_concert(params)
      @songs = params[:songs]
      @concert_info = params[:concert].split(', ')
      if @concert_info.size > 4
        @venue = Venue.find_or_create_by(name: @concert_info[2] || "n/a", city: @concert_info[3] || "n/a", state: @concert_info[4] || "n/a")
        @concert = Concert.find_or_create_by(date: @concert_info[0], venue_id: @venue.id)
        @concert_artist = ConcertArtist.find_or_create_by(concert_id: @concert.id, artist_id: @band.id)
        @date = @concert.date.strftime('%B %e %Y')
        @tour = @concert_info[1]
      else
        @venue = Venue.find_or_create_by(name: @concert_info[1] || "n/a", city: @concert_info[2] || "n/a", state: @concert_info[3] || "n/a")
        @concert = Concert.find_or_create_by(date: @concert_info[0], venue_id: @venue.id)
        @concert_artist = ConcertArtist.find_or_create_by(concert_id: @concert.id, artist_id: @band.id)
        @date = @concert.date.strftime('%B %e %Y')
      end

      @playlist = CreatePlaylist.new("#{@band.name} live at #{@venue.name}, #{@venue.city}, #{@venue.state}, #{@concert.date.strftime('%B %e, %Y')}")
      @playlist_id = @playlist.make_playlist.playlist_id
      @concert.update(yt_playlist: @playlist_id)

      if @songs.is_a? Array
        @songs.each_with_index do |song_name, i|
          next if song_name.nil?
          song = Song.find_or_create_by(title: song_name, artist_id: @band.id)
          ConcertSong.find_or_create_by(concert_id: @concert.id, song_id: song.id, order: i)
        end
      elsif @songs.is_a? String
        @songs = [@songs]
        song = Song.find_or_create_by(title: @songs, artist_id: @band.id)
        ConcertSong.find_or_create_by(concert_id: @concert.id, song_id: song.id, order: 1)
      end

    end
end

app/helpers/searches_helper.rb
module SearchesHelper

	def date(concert) 
		concert_date = concert.split(",")[0]
		formatted_date = concert_date.split(" ")
		date = "#{formatted_date[0]} #{formatted_date[1]}, #{formatted_date[2]}"
		return date
	end

	def venue(concert) 
		concert_venue = concert.split(",")[1]
		return concert_venue
	end

	def location(concert) 
		city = concert.split(",")[2]
		state = concert.split(",")[3]
		return "#{city}, #{state}"
	end

	def song_truncate(song)
		if song.length > 25
			displayed_song = song[0..25]
		else 
			displayed_song = song 
		end
		return displayed_song
	end

end

app/views/searches/_concert_listing.html.erb
<li class="concert-listing">
  <%= link_to(search_youtube_path(band: band.name, concert: concert, songs: songs), id: 'concert-title') do  %>
    <h3><%= date(concert) %><h3><h4><br><%= venue(concert)%><br><%=location(concert)%></h4>
  <% end %>
</li>

app/views/searches/index.html.erb
<div class="jumbotron">
  <center><h1>Relive your favorite concerts</h1>

  <%= form_tag '/search', method: "get", html: { class: "form-horizontal" } do %>
    <%= hidden_field_tag :page, 1 %>
    <div class="form-group">
      <h2><%= label_tag :band, "Search for concerts now" %></h2><br>
      <%= text_field_tag :band, nil, placeholder: "Artist name", id: "myinput", class: 'form-control' %>
    </div>
    <br>
    <%= submit_tag "Search", class: "search-button" %>

  <% end %>

  </center>

  <!-- <div id="howitworks">
  	<h1>Getting Started...</h1>
  	<div class="home-left">
  		<%= icon('search')%>
  		<h3>Lorem Ipsum</h3>
  		<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
  	</div>
  	<div class="home-center">
  		<%= icon('group') %>
  		<h3>Lorem Ipsum</h3>
  		<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
  	</div>
  	<div class="home-right">
  		<%= icon('ticket') %>
  		<h3>Lorem Ipsum</h3>
  		<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
  	</div>
  </div> -->

  <div id="suggestion" >
    Questions, comments, or suggestions? Please <%= mail_to("EncoreBetaTesting@gmail.com", "email", subject: "Encore Website Suggestions") %> us
  </div>

</div>

app/views/searches/search.html.erb
<div id="search-page">
  <h1>Concerts for <%= @band.name %></h1>

  <div class="upper-left-nav">
    <% unless params[:page].to_i == 1 %>
    <%= link_to icon('angle-left'), search_path(band: @band.name, page: params[:page].to_i - 1), class: 'load-more-concerts' %>
    <% end %>
  </div>

  <% if params[:page].to_i < @max_pages %>
    <div class="upper-nav">
      <%= link_to icon('angle-right'), search_path(band: @band.name, page: params[:page].to_i + 1), class: 'load-more-concerts' %>
      <br>
    </div>
  <% end %>

    <ul class="concert-listings">
      <% @results.each do |concert, songs| %>
        <%= render partial: "concert_listing", locals: { band: @band, concert: concert, songs: songs } %>
      <% end %>
    </ul>

    <div class="lower-left-nav">
      <% unless params[:page].to_i == 1 %>
        <%= link_to icon('angle-left'), search_path(band: @band.name, page: params[:page].to_i - 1), class: 'load-more-concerts' %>
      <% end %>
    </div>

    <% if params[:page].to_i < @max_pages %>
      <div class="lower-nav">
        <%= link_to icon('angle-right'), search_path(band: @band.name, page: params[:page].to_i + 1), class: 'load-more-concerts' %>
      </div>
    <% end %>
</div>

app/views/searches/search_youtube.html.erb
<div class="outside">
  <div class="concert-header">
    <h2><%= @band.name %></h2><h3><%= @date %></h3><h4><%= @venue.name %><br><%= @venue.city %>, <%= @venue.state %></h4>
    <button><%= link_to "Go To Concert", concert_path(@concert) %></a></button>
    <br>
  </div>

  <div class="videos">
    <div class="video-list">
      <% @titles_ids.each do |title, id| %>

        <%= form_for :song, url: songs_path, method: :post, html: { class: 'add-song' } do |f| %>
          <%= f.hidden_field :id, value: id %>

          <div class="youtube" id="<%= id %>" style="width: 320px; height: 180px;"></div>

          <div class="video-form">
              <p><i>Youtube Title:</i> <b id='yt-title'><%= title %></b></p>
              <label for="song">Choose song title for this video:</label>
              <!-- Check to see if the song array with the songs in the setlist
                    is empty. The songs array will be [""] if there is no setlist for this show. -->
            <% if @songs.nil? %>

              <%= f.text_field :song, value: title %>

              <%= f.submit "Add Video To Concert" %>
              <hr>
              <!-- Otherwise, you can select the song based on the setlist. -->
            <% else %>
              <%= f.select :songs, @songs.collect { |song| song } %>
              <%= f.submit "Add Video To Concert", id: "add-song" %>
              <a href="#" class="remove-video">Not Relevant?</a>
            <% end %><!--End for the @songs selection loop -->
          <% end %>
          </div>
      <% end %><!--End for the @titles_id.each loop -->
    </div>
    <div class="setlist-container">
      <div class="setlist">
        <h3>Setlist</h3>
        <ol class="set-songs">
        <% @songs.each do |song| %>
          <li class="set-song"><%= song_truncate(song) %><%= icon('square-o')%></li>
        <% end %>
        </ol>
      </div>
    </div>
  </div>


</div>
<script type="text/javascript" src="https://labnol.googlecode.com/files/youtube.js"></script>

<script type="text/javascript">
  var concertId = <%= @concert_artist.concert_id %>;
  var artistId = <%= @concert_artist.artist_id %>;
  var playlistId = "<%= @playlist_id %>";
</script>