config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  root to: "searches#index"

  post 'flag_video', to: 'concerts#flag_video', as: 'flag_video'
  post 'unflag_video', to: 'concerts#unflag_video', as: 'unflag_video'
  get 'search', to: 'searches#search', as: 'search'
  get 'search_youtube', to: 'searches#search_youtube', as: 'search_youtube'
  get 'search_setlist', to: 'searches#search_setlist', as: 'search_setlist'
  resources :concerts, only: [:new, :create, :show]
  resources :venues, only: [:new, :create]
  resources :artists, only: [:new, :create]
  resources :songs, only: [:new, :create]
  resources :concert_songs, only: [:create]

  post 'create_concert', to: 'concerts#create', as: 'create_concert'

  resources :users, only: [:index, :show]

  resources :attended_concerts, only: [:create]

  resources :relationships, only: [:create] do
    collection do
      post '/unfollow', to: "relationships#unfollow"
    end
  end

  resources :concert_photos, only: [:create, :destroy]

  resources :pages, only: [:index]
  get 'about', to: 'pages#index', as: 'about'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
  has_many :concert_artists
  has_many :concerts, through: :concert_artists
end

app/models/attended_concert.rb
class AttendedConcert < ActiveRecord::Base
  validates :concert_id, presence: true
  validates :user_id, presence: true

  belongs_to :concert
  belongs_to :user

  validates_uniqueness_of :concert_id, scope: :user_id
end

app/models/concert.rb
class Concert < ActiveRecord::Base
  validates :date, presence: true
  validates :venue_id, presence: true

  belongs_to :venue

  has_many :concert_artists
  has_many :artists, through: :concert_artists

  has_many :concert_songs
  has_many :songs, through: :concert_songs

  has_many :attended_concerts
  has_many :users, through: :attended_concerts

  has_many :concert_photos

end

app/models/concert_artist.rb
class ConcertArtist < ActiveRecord::Base
  validates :concert_id, presence: true
  validates :artist_id, presence: true

  belongs_to :concert
  belongs_to :artist

  validates_uniqueness_of :concert_id, scope: :artist_id
end

app/models/concert_photo.rb
class ConcertPhoto < ActiveRecord::Base
  belongs_to :user
  belongs_to :concert

  mount_uploader :image, ConcertPhotoUploader 
end

app/models/concert_song.rb
class ConcertSong < ActiveRecord::Base
  validates :concert_id, presence: true
  validates :song_id, presence: true

  belongs_to :concert
  belongs_to :song

  has_many :videos

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true

  validates_uniqueness_of :follower, scope: :followed

end

app/models/setlist.rb
class Setlist < ActiveRecord::Base
  belongs_to :concert
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :artist_id, presence: true

  belongs_to :artist

  has_many :concert_songs
  has_many :concerts, through: :concert_song
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true
  validates :email, uniqueness: true

  has_many :attended_concerts
  has_many :concerts, through: :attended_concerts

  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed

  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  has_many :concert_photos

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  #being used in the user_controller.rb
  def followers(user_id)

    relationships = Relationship.where(followed_id: user_id)
    followers = relationships.map { |relationship| User.find(relationship.follower_id) }
    return followers

  end

  #being used in the user_controller.rb
  def following(user_id)

    relationships = Relationship.where(follower_id: user_id)
    followed_users = relationships.map { |relationship|  User.find(relationship.followed_id) }
    return followed_users

  end

  #being used in the users/index.html.erb
  def following?(user_id)
    relationships.exists?(followed_id: user_id)
  end


  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  validates :name, :city, :state, presence: true

  has_many :concerts
end

app/models/video.rb
class Video < ActiveRecord::Base

  after_update :send_flag_email

  validates :identifier, presence: true
  validates :concert_song_id, presence: true

  belongs_to :concert_song

  private

    def send_flag_email
      if self.correct == false
        FlaggedVideoMailer.video_flagged(self.concert_song.concert, self).deliver
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def create
    artist = Artist.find(params[:artist_id])
    concert = Concert.find(params[:concert_id])
    song = Song.find_by(title: params[:song], artist_id: artist.id)
    concert_song = concert.concert_songs.find_by(song_id: song.id)

    add_video(params[:song_id], concert_song)
    CreatePlaylist.new.add_video(concert.yt_playlist, params[:song_id])
    # playlist.add_videos(@concert.concert_songs)

    render text: "Song added!"
  end

  private
    def add_video(identifier, concert_song)
      video = Video.find_or_initialize_by(identifier: identifier)
      video.concert_song_id = concert_song.id
      video.save!
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
      @users = User.where.not(id: current_user.id)
    end

    def show
      @user = User.find(params[:id])
      @concerts = @user.concerts.order('date DESC')
      unless @concerts == []
        @year = @concerts.first.date.strftime('%Y')
      end

      @followers = @user.followers(params[:id]).each { |person| person}

      @users_following = @user.following(params[:id]).each { |person| person }

    end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  def new
  end

  def create
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
	def body_classes
    "#{controller.controller_name} #{controller.action_name}"
	end
end

app/helpers/searches_helper.rb
module SearchesHelper

	def date(concert) 
		concert_date = concert.split(",")[0]
		formatted_date = concert_date.split(" ")
		date = "#{formatted_date[0]} #{formatted_date[1]}, #{formatted_date[2]}"
		return date
	end

	def venue(concert) 
		concert_venue = concert.split(",")[1]
		return concert_venue
	end

	def location(concert) 
		city = concert.split(",")[2]
		state = concert.split(",")[3]
		return "#{city}, #{state}"
	end

	def song_truncate(song)
		if song.length > 25
			displayed_song = song[0..25]
		else 
			displayed_song = song 
		end
		return displayed_song
	end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Encore</title>
  <link href="//fonts.googleapis.com/css?family=Source+Sans Pro:200italic,200,300italic,300,400italic,400,600italic,600,700italic,700,900italic,900" rel="stylesheet" type="text/css">
  <link href="//fonts.googleapis.com/css?family=Lato:100italic,100,300italic,300,400italic,400,700italic,700,900italic,900" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Just+Another+Hand" rel="stylesheet" type="text/css">
  <%= favicon_link_tag 'ticket-16.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <!-- Code for Google Freebase Search -->
  <link type="text/css" rel="stylesheet" href="https://www.gstatic.com/freebase/suggest/4_2/suggest.min.css" />
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore-min.js"></script>
  <script type="text/javascript" src="https://www.gstatic.com/freebase/suggest/4_2/suggest.min.js"></script>

  <script type="text/javascript">
  $(function() {
    $("#myinput").suggest({ "key" : "AIzaSyDc5jAEx4GRNRtZHyOMEDJiYmPAGohDi2w",
                            filter:'(all type:/music/artist)'
                          });
  });
  </script>

</head>
<body class="<%= body_classes %>">
    <nav>
      <ul>
        <h1><a href="/" class="headline">ENCORE</a></h1>
        <% if current_user %>
          <li class="current_user">
            <%= link_to user_path(session[:user_id]) do %>
              <strong><%= current_user.name %></strong>
            <% end %>
          </li>
          <li class="sign-out-button">
            <%= link_to signout_path, id: "sign_out" do %>
              <strong>Sign Out</strong>
            <% end %>
          </li>
          <% else %>
            <li><%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %></li>
        <% end %>
        </li>
      </ul>
    </nav>



  <div class="container">

    <div id='flash'>
      <% flash.each do |type, msg| %>
      <div class="alert alert-<%= type %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      </div>
      <% end %>
    </div>

    <%= yield %>

  </div>

</body>
</html>

app/views/pages/index.html.erb
<div id="about_intro">
  <h1 class="about_title">Encore is for the ones...</h1>

  <h2>Who feel at home amongst thousands of strangers, all getting lost in the power and emotion of live music.</h2>
  <br>
  <h2>Who drop all prior obligations when tickets to their favorite artist go on sale.­­­­</h2>
  <br>
  <h2>Whose vacation paradise is sleeping in a tent where the music doesn’t stop until sunrise.</h2>
  <br>
  <h2>Who aren’t content with letting the memories fade once the encore is played.</h2>
  <br>

  <div id="a_b">
    <%= image_tag("above_and_beyond.png", :alt => "above_and_beyond") %>
  </div>
</div>

<div id="about_story">
  <h1 class="about_title">Our Story</h1>

  <h2>Encore was born out of the idea of having a place to relive and share all of your favorite concert memories. While the moments themselves can never be recreated, having a community to save all of the pieces is something we wanted to create. We hope that you use this site as a means of remembering your favorite shows, and sharing them with others.</h2>
</div>

<div id="about_team">
  <h1 class="about_title">Our Team</h1>
    <div class="team_member first_member">
      <h2>Brendan Scarano</h2>
        <div id="brendan">
          <%#= image_tag("brendan2.png", :alt => "brendan") %>
      <a href="http://www.linkedin.com/in/brendanscarano"><%= icon('linkedin')%></a>
      <a href="https://github.com/Onaracs"><%= icon('github')%></a>
        </div>
      <br>
      <div class="favorite_concert">
        <br>
        <h2>Favorite Concert</h2>
        <br>
        <h2>AC/DC</h2>
        <h2>Madison Square Garden</h2>
        <h2>November 12, 2008</h2>
      </div>


    </div>

    <div class="team_member">
      <h2>Jared Rader</h2>
        <div id="jared">
          <%#= image_tag("jared.png", :alt => "jared") %>
      <a href="http://www.linkedin.com/pub/jared-rader/39/b32/14b"><%= icon('linkedin')%></a>
      <a href="https://github.com/raderj89"><%= icon('github')%></a>
        </div>
      <br>

      <div class="favorite_concert">
        <br>
        <h2>Favorite Concert</h2>
        <br>
        <h2>Roger Waters The Wall</h2>
        <h2>American Airlines Center</h2>
        <h2>November 21, 2010</h2>
      </div>

    </div>

    <div class="team_member">
      <h2>Buck O'Leary</h2>
        <div id="buck">
          <%#= image_tag("buck.png", :alt => "buck") %>
      <a href="http://www.linkedin.com/pub/howard-o-leary/35/893/722"><%= icon('linkedin')%></a>
      <a href="https://github.com/buck3000"><%= icon('github')%></a>
        </div>


      <div class="favorite_concert">
        <br>
        <h2>Favorite Concert</h2>
        <br>
        <h2>The Black Keys</h2>
        <h2>Constant Convocation Center</h2>
        <h2>March 23, 2012</h2>
      </div>



    </div>

    <div class="team_member">
      <h2>Timmy Haung</h2>
        <div id="timmy">
          <%#= image_tag("timmy.png", :alt => "timmy") %>
        <a href="http://www.linkedin.com/in/tihuan"><%= icon('linkedin')%></a>
        <a href="https://github.com/tihuan"><%= icon('github')%></a>
        </div>
        <br>
        <div class="favorite_concert">
          <h2>Favorite Concert</h2>
          <br>
          <h2>Armin Van Buuren</h2>
          <h2>Escape From Wonderland</h2>
          <h2>October 27, 2012</h2>
        </div>


    </div>



</div>

<%#= image_tag("a_b2.png", :alt => "concert") %>
<%#= image_tag("acdc2.png", :alt => "concert") %>